if: branch = master

language: node_js
node_js:
  - "node"

env:
  - NODE_OPTIONS=--openssl-legacy-provider

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
