name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: larssonoliverdotcom-runner-set
    container: node:22
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
