name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Dependency Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
